# Generated by Django 3.1.4 on 2021-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_database', '0003_auto_20210616_1344'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clinicalindication',
            name='clinical_in_version_6ddffd_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalindicationpanels',
            name='clinical_in_clinica_9b5ae9_idx',
        ),
        migrations.RemoveField(
            model_name='clinicalindication',
            name='version',
        ),
        migrations.AddField(
            model_name='clinicalindicationpanels',
            name='ci_version',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='clinicalindicationpanels',
            index=models.Index(fields=['clinical_indication', 'panel', 'ci_version'], name='clinical_in_clinica_6cfee4_idx'),
        ),
    ]
