# Generated by Django 3.1.4 on 2021-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_database', '0003_auto_20210616_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalindicationpanels',
            name='version',
            field=models.CharField(default='', max_length=100),
        ),
    ]
