# Generated by Django 3.1.4 on 2023-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_database', '0004_auto_20210701_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
